apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: alpine:latest
          command: ["sh", "-c", "while true; do echo \"$(date +'%Y/%m/%d %H:%M:%S') - ENV=${ENV}\"; sleep 5s; done"]
          envFrom:
            - secretRef:
                name: demo-dev
          resources: 
            requests: 
              cpu: 10m
              memory: 32Mi
            limits: 
              cpu: 100m
              memory: 120Mi
